name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Push, and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Container Registry
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Build and Push Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:latest .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:latest

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy test-workflow \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:latest \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --port 3000 \
          --allow-unauthenticated \
          --set-env-vars CLOUD_STORAGE_SERVICE_ACCOUNT="$(cat ${HOME}/cloud_storage.json | base64)" \
          --set-env-vars FIREBASE_SERVICE_ACCOUNT="$(cat ${HOME}/firebase.json | base64)"
      env:
        CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
        CLOUDSDK_METRICS_ENVIRONMENT_VERSION: 1.1.1
